In [2]:
import pandas as pd
train = pd.read_pickle('dataframes/591_train_0_12_1.pkl')
train

,bg_value__variance_larger_than_standard_deviation,bg_value__has_duplicate_max,bg_value__has_duplicate_min,bg_value__has_duplicate,bg_value__sum_values,bg_value__abs_energy,bg_value__mean_abs_change,bg_value__mean_change,bg_value__mean_second_derivative_central,bg_value__median,...,"bg_value__matrix_profile__feature_""75""__threshold_0.98",bg_value__mean_n_absolute_max__number_of_maxima_7,start,end,start_time,end_time,start_time_of_day,end_time_of_day,part_of_day,label
0,1.0,0.0,0.0,1.0,2183.0,400947.0,5.818182,5.272727,0.95,185.0,...,NaN,194.857143,0,11,0.00,0.92,17:06:00,18:01:00,evening,226
1,1.0,0.0,0.0,1.0,2249.0,426423.0,6.363636,6.181818,0.30,189.5,...,NaN,201.142857,1,12,0.08,1.00,17:11:00,18:06:00,evening,231
2,1.0,0.0,0.0,1.0,2322.0,454820.0,6.636364,6.454545,-0.05,191.5,...,NaN,207.285714,2,13,0.17,1.08,17:16:00,18:11:00,evening,245
3,1.0,0.0,0.0,1.0,2407.0,489245.0,7.363636,7.181818,0.25,192.0,...,NaN,215.000000,3,14,0.25,1.17,17:21:00,18:16:00,evening,238
4,1.0,0.0,0.0,1.0,2479.0,518333.0,7.181818,5.727273,-0.70,196.5,...,NaN,221.571429,4,15,0.33,1.25,17:26:00,18:21:00,evening,237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10830,1.0,0.0,0.0,0.0,2689.0,607067.0,10.272727,-1.000000,1.60,223.5,...,NaN,237.428571,10830,10841,1061.53,1062.45,22:38:00,23:33:00,night,266
10831,1.0,0.0,0.0,0.0,2697.0,611259.0,11.181818,1.545455,1.70,223.5,...,NaN,238.571429,10831,10842,1061.62,1062.53,22:43:00,23:38:00,night,275
10832,1.0,0.0,0.0,0.0,2723.0,624883.0,10.636364,3.727273,0.80,223.5,...,NaN,242.285714,10832,10843,1061.70,1062.62,22:48:00,23:43:00,night,268
10833,1.0,0.0,0.0,0.0,2757.0,641951.0,10.636364,3.727273,-0.15,223.5,...,NaN,247.142857,10833,10844,1061.78,1062.70,22:53:00,23:48:00,night,301
10834,1.0,0.0,0.0,0.0,2831.0,681023.0,13.272727,7.090909,1.85,223.5,...,NaN,257.714286,10834,10845,1061.87,1062.78,22:58:00,23:53:00,night,290

In [1]:
from pycaret.regression import *

In [5]:
import numpy as np
train.replace([np.inf, -np.inf], np.nan, inplace=True)
train.dropna(how='all', axis=1, inplace=True)

In [7]:
train

,bg_value__variance_larger_than_standard_deviation,bg_value__has_duplicate_max,bg_value__has_duplicate_min,bg_value__has_duplicate,bg_value__sum_values,bg_value__abs_energy,bg_value__mean_abs_change,bg_value__mean_change,bg_value__mean_second_derivative_central,bg_value__median,...,bg_value__permutation_entropy__dimension_7__tau_1,bg_value__mean_n_absolute_max__number_of_maxima_7,start,end,start_time,end_time,start_time_of_day,end_time_of_day,part_of_day,label
0,1.0,0.0,0.0,1.0,2183.0,400947.0,5.818182,5.272727,0.95,185.0,...,1.791759,194.857143,0,11,0.00,0.92,17:06:00,18:01:00,evening,226
1,1.0,0.0,0.0,1.0,2249.0,426423.0,6.363636,6.181818,0.30,189.5,...,1.791759,201.142857,1,12,0.08,1.00,17:11:00,18:06:00,evening,231
2,1.0,0.0,0.0,1.0,2322.0,454820.0,6.636364,6.454545,-0.05,191.5,...,1.791759,207.285714,2,13,0.17,1.08,17:16:00,18:11:00,evening,245
3,1.0,0.0,0.0,1.0,2407.0,489245.0,7.363636,7.181818,0.25,192.0,...,1.791759,215.000000,3,14,0.25,1.17,17:21:00,18:16:00,evening,238
4,1.0,0.0,0.0,1.0,2479.0,518333.0,7.181818,5.727273,-0.70,196.5,...,1.791759,221.571429,4,15,0.33,1.25,17:26:00,18:21:00,evening,237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10830,1.0,0.0,0.0,0.0,2689.0,607067.0,10.272727,-1.000000,1.60,223.5,...,1.242453,237.428571,10830,10841,1061.53,1062.45,22:38:00,23:33:00,night,266
10831,1.0,0.0,0.0,0.0,2697.0,611259.0,11.181818,1.545455,1.70,223.5,...,1.560710,238.571429,10831,10842,1061.62,1062.53,22:43:00,23:38:00,night,275
10832,1.0,0.0,0.0,0.0,2723.0,624883.0,10.636364,3.727273,0.80,223.5,...,1.791759,242.285714,10832,10843,1061.70,1062.62,22:48:00,23:43:00,night,268
10833,1.0,0.0,0.0,0.0,2757.0,641951.0,10.636364,3.727273,-0.15,223.5,...,1.791759,247.142857,10833,10844,1061.78,1062.70,22:53:00,23:48:00,night,301
10834,1.0,0.0,0.0,0.0,2831.0,681023.0,13.272727,7.090909,1.85,223.5,...,1.791759,257.714286,10834,10845,1061.87,1062.78,22:58:00,23:53:00,night,290

In [6]:
setup(data=train)

In [8]:
compare_models()