In [1]:
import pandas as pd
train = pd.read_pickle('dataframes/591_train_0_12_1.pkl')
train

,bg_value__variance_larger_than_standard_deviation,bg_value__has_duplicate_max,bg_value__has_duplicate_min,bg_value__has_duplicate,bg_value__sum_values,bg_value__abs_energy,bg_value__mean_abs_change,bg_value__mean_change,bg_value__mean_second_derivative_central,bg_value__median,...,"bg_value__matrix_profile__feature_""75""__threshold_0.98",bg_value__mean_n_absolute_max__number_of_maxima_7,start,end,start_time,end_time,start_time_of_day,end_time_of_day,part_of_day,label
0,1.0,0.0,0.0,1.0,2183.0,400947.0,5.818182,5.272727,0.95,185.0,...,NaN,194.857143,0,11,0.00,0.92,17:06:00,18:01:00,evening,226
1,1.0,0.0,0.0,1.0,2249.0,426423.0,6.363636,6.181818,0.30,189.5,...,NaN,201.142857,1,12,0.08,1.00,17:11:00,18:06:00,evening,231
2,1.0,0.0,0.0,1.0,2322.0,454820.0,6.636364,6.454545,-0.05,191.5,...,NaN,207.285714,2,13,0.17,1.08,17:16:00,18:11:00,evening,245
3,1.0,0.0,0.0,1.0,2407.0,489245.0,7.363636,7.181818,0.25,192.0,...,NaN,215.000000,3,14,0.25,1.17,17:21:00,18:16:00,evening,238
4,1.0,0.0,0.0,1.0,2479.0,518333.0,7.181818,5.727273,-0.70,196.5,...,NaN,221.571429,4,15,0.33,1.25,17:26:00,18:21:00,evening,237
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10830,1.0,0.0,0.0,0.0,2689.0,607067.0,10.272727,-1.000000,1.60,223.5,...,NaN,237.428571,10830,10841,1061.53,1062.45,22:38:00,23:33:00,night,266
10831,1.0,0.0,0.0,0.0,2697.0,611259.0,11.181818,1.545455,1.70,223.5,...,NaN,238.571429,10831,10842,1061.62,1062.53,22:43:00,23:38:00,night,275
10832,1.0,0.0,0.0,0.0,2723.0,624883.0,10.636364,3.727273,0.80,223.5,...,NaN,242.285714,10832,10843,1061.70,1062.62,22:48:00,23:43:00,night,268
10833,1.0,0.0,0.0,0.0,2757.0,641951.0,10.636364,3.727273,-0.15,223.5,...,NaN,247.142857,10833,10844,1061.78,1062.70,22:53:00,23:48:00,night,301
10834,1.0,0.0,0.0,0.0,2831.0,681023.0,13.272727,7.090909,1.85,223.5,...,NaN,257.714286,10834,10845,1061.87,1062.78,22:58:00,23:53:00,night,290

In [2]:
from pycaret.regression import *

In [3]:
import numpy as np
train.replace([np.inf, -np.inf], np.nan, inplace=True)
train.dropna(how='all', axis=1, inplace=True)
reg = setup(
    data=train,
    target='label',
    normalize=True,
    ignore_features=['start', 'end', 'start_time', 'end_time', 'start_time_of_day', 'end_time_of_day']
    # feature_selection=True
)

In [ ]:
reg

In [4]:
dt = create_model('dt')

In [ ]:
dt

In [ ]:
type(dt)

In [5]:
pred = predict_model(dt)

In [6]:
pred

,bg_value__variance_larger_than_standard_deviation,bg_value__has_duplicate_max,bg_value__has_duplicate_min,bg_value__has_duplicate,bg_value__sum_values,bg_value__abs_energy,bg_value__mean_abs_change,bg_value__mean_change,bg_value__mean_second_derivative_central,bg_value__median,...,bg_value__fourier_entropy__bins_100,bg_value__permutation_entropy__dimension_3__tau_1,bg_value__permutation_entropy__dimension_4__tau_1,bg_value__permutation_entropy__dimension_5__tau_1,bg_value__permutation_entropy__dimension_6__tau_1,bg_value__permutation_entropy__dimension_7__tau_1,bg_value__mean_n_absolute_max__number_of_maxima_7,part_of_day,label,prediction_label
5665,1.0,0.0,0.0,1.0,2082.0,361650.0,5.272727,0.000000,0.30,172.0,...,1.747868,1.279854,1.735126,1.732868,1.747868,1.791759,177.000000,late night,177,170.0
217,1.0,1.0,0.0,1.0,1733.0,250669.0,4.000000,0.909091,-0.65,147.0,...,1.153742,1.418484,1.889159,2.079442,1.945910,1.791759,149.000000,morning,143,142.0
9911,1.0,1.0,0.0,1.0,2339.0,457383.0,4.727273,3.454545,-0.90,192.0,...,1.475076,0.940448,1.303092,1.667462,1.747868,1.791759,202.000000,evening,209,214.0
1280,1.0,0.0,0.0,1.0,1242.0,128644.0,2.545455,-0.181818,-0.05,104.0,...,1.747868,1.470809,1.676988,1.906155,1.945910,1.791759,105.571426,late night,106,104.0
5749,1.0,1.0,0.0,1.0,2814.0,659972.0,1.636364,-0.727273,-0.05,236.0,...,1.945910,1.504788,2.043192,2.079442,1.945910,1.791759,236.285721,afternoon,230,227.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8178,1.0,0.0,0.0,0.0,1594.0,287258.0,37.454544,16.363636,0.75,112.0,...,1.945910,1.418484,2.043192,2.079442,1.945910,1.791759,173.000000,night,305,280.0
3881,1.0,0.0,0.0,1.0,1641.0,224793.0,2.454545,-1.000000,0.30,134.5,...,1.475076,1.220607,1.581094,1.667462,1.747868,1.791759,139.857147,night,154,142.0
7904,1.0,0.0,1.0,1.0,825.0,58275.0,4.454545,1.545455,-0.40,71.0,...,1.475076,0.940448,1.002718,1.073543,1.153742,1.242453,77.428574,morning,72,82.0
3209,1.0,0.0,0.0,1.0,1443.0,174231.0,2.727273,2.000000,0.40,119.5,...,1.549826,0.639032,0.683739,0.735622,0.796312,0.867563,125.142860,morning,140,150.0
10025,1.0,0.0,0.0,1.0,1564.0,204118.0,2.272727,-1.545455,0.20,129.0,...,1.945910,1.359237,1.676988,1.906155,1.945910,1.791759,133.142853,late night,124,122.0

In [ ]:
type(pred)

In [7]:
reg[9] #test dataframe

TypeError: 'RegressionExperiment' object is not subscriptable

In [ ]:
reg[1]

In [ ]:
train[1:2]

In [ ]:
predict_model(dt, train[7630:7640])

In [ ]:
plot_model(dt, 'feature')

In [ ]:
test_1 = train.iloc[reg[9].index]
test_1

In [ ]:
pred2 = predict_model(dt, test_1)
pred2

In [ ]:
pred_day = pred2[['part_of_day', 'label', 'Label']]
pred_day['residual'] = pred_day['Label'] - pred_day['label']
pred_day

In [ ]:
pred_day.to_excel('pred_day.xlsx')